# Generated by Django 6.0.2 on 2026-02-19 08:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("handle", models.SlugField(max_length=80, unique=True)),
                ("display_name", models.CharField(max_length=120)),
                ("avatar_url", models.URLField(blank=True, max_length=600)),
                ("bio", models.TextField(blank=True, default="")),
                ("followers", models.PositiveIntegerField(default=0)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={"verbose_name": "Profile", "verbose_name_plural": "Profiles",},
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(blank=True, default="", max_length=700)),
                ("s3_key", models.CharField(blank=True, default="", max_length=500)),
                ("caption", models.TextField(default="")),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "original_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("food", "Food & Dining"),
                            ("shopping", "Shopping"),
                            ("travel", "Travel"),
                            ("entertainment", "Entertainment"),
                            ("transport", "Transport"),
                            ("utilities", "Utilities"),
                            ("health", "Health"),
                            ("education", "Education"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("tag", models.CharField(blank=True, default="", max_length=50)),
                (
                    "media_label",
                    models.CharField(
                        choices=[
                            ("Post", "Post"),
                            ("Story", "Story"),
                            ("Reel", "Reel"),
                        ],
                        default="Post",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, default="", max_length=140)),
                ("likes", models.PositiveIntegerField(default=0)),
                ("comments", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="social.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
                "ordering": ("-created_at",),
            },
        ),
    ]
