# Generated by Django 6.0.2 on 2026-02-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="clerk_user_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=200
            ),
        ),
    ]
