# Generated by Django 6.0.2 on 2026-02-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_profile_clerk_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="ai_analysis",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
