# Generated by Django 6.0.2 on 2026-02-19 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0005_comment_edited_at_like"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("s3_key", models.CharField(blank=True, default="", max_length=500)),
                ("image_url", models.URLField(blank=True, default="", max_length=700)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="social.post",
                    ),
                ),
            ],
            options={"ordering": ("order",),},
        ),
    ]
